In [11]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/dataset.csv")

print("Shape:", df.shape)

df.head()

Shape: (1040, 18)

,village_id,village_name,latitude,longitude,population,water_source_type,date,ph_level,turbidity_ntu,residual_chlorine_mg_l,bacterial_contamination,rainfall_mm,temperature_c,sanitation_index,historical_cases_last_4_weeks,disease_type,case_count,outbreak_risk_level
0,V001,Village_1,16.57454,74.31185,10470,pond,2024-01-07,6.84,1.95,0.456,0,13.1,32.4,0.34,0,diarrhea,8,High
1,V001,Village_1,16.57454,74.31185,10470,pond,2024-01-14,7.33,2.31,0.462,0,6.4,25.7,0.34,8,typhoid,18,High
2,V001,Village_1,16.57454,74.31185,10470,pond,2024-01-21,5.94,2.49,0.326,0,5.4,28.9,0.34,18,diarrhea,6,Medium
3,V001,Village_1,16.57454,74.31185,10470,pond,2024-01-28,6.58,1.78,0.382,0,8.6,28.0,0.34,6,cholera,2,Low
4,V001,Village_1,16.57454,74.31185,10470,pond,2024-02-04,6.99,2.84,0.274,0,7.0,37.4,0.34,2,hepatitis_a,6,Medium

In [12]:
df["date"] = pd.to_datetime(df["date"])
print(df["date"].dtype)

datetime64[us]

In [14]:
df.isnull().sum()

village_id                       0
village_name                     0
latitude                         0
longitude                        0
population                       0
water_source_type                0
date                             0
ph_level                         0
turbidity_ntu                    0
residual_chlorine_mg_l           0
bacterial_contamination          0
rainfall_mm                      0
temperature_c                    0
sanitation_index                 0
historical_cases_last_4_weeks    0
disease_type                     0
case_count                       0
outbreak_risk_level              0
dtype: int64

In [16]:
print("Duplicate rows:", df.duplicated().sum())
df = df.drop_duplicates()
print("Shape after removing duplicates:", df.shape)

Duplicate rows: 0
Shape after removing duplicates: (1040, 18)

In [17]:
df = df.sort_values(by=["village_id", "date"])
df = df.reset_index(drop=True)
df.head(10)

,village_id,village_name,latitude,longitude,population,water_source_type,date,ph_level,turbidity_ntu,residual_chlorine_mg_l,bacterial_contamination,rainfall_mm,temperature_c,sanitation_index,historical_cases_last_4_weeks,disease_type,case_count,outbreak_risk_level
0,V001,Village_1,16.57454,74.31185,10470,pond,2024-01-07,6.84,1.95,0.456,0,13.1,32.4,0.34,0,diarrhea,8,High
1,V001,Village_1,16.57454,74.31185,10470,pond,2024-01-14,7.33,2.31,0.462,0,6.4,25.7,0.34,8,typhoid,18,High
2,V001,Village_1,16.57454,74.31185,10470,pond,2024-01-21,5.94,2.49,0.326,0,5.4,28.9,0.34,18,diarrhea,6,Medium
3,V001,Village_1,16.57454,74.31185,10470,pond,2024-01-28,6.58,1.78,0.382,0,8.6,28.0,0.34,6,cholera,2,Low
4,V001,Village_1,16.57454,74.31185,10470,pond,2024-02-04,6.99,2.84,0.274,0,7.0,37.4,0.34,2,hepatitis_a,6,Medium
5,V001,Village_1,16.57454,74.31185,10470,pond,2024-02-11,7.22,1.97,0.351,0,2.3,31.1,0.34,6,diarrhea,2,Low
6,V001,Village_1,16.57454,74.31185,10470,pond,2024-02-18,7.21,0.43,0.307,0,19.9,32.6,0.34,2,typhoid,12,High
7,V001,Village_1,16.57454,74.31185,10470,pond,2024-02-25,7.06,2.64,0.400,0,3.0,30.0,0.34,12,cholera,14,High
8,V001,Village_1,16.57454,74.31185,10470,pond,2024-03-03,7.07,2.49,0.229,0,7.9,32.5,0.34,14,hepatitis_a,6,Medium
9,V001,Village_1,16.57454,74.31185,10470,pond,2024-03-10,6.25,1.06,0.342,0,2.2,34.0,0.34,6,typhoid,10,High

In [18]:
df[["ph_level", "turbidity_ntu", "residual_chlorine_mg_l", "rainfall_mm", "case_count"]].describe()

,ph_level,turbidity_ntu,residual_chlorine_mg_l,rainfall_mm,case_count
count,1040.000000,1040.000000,1040.000000,1040.000000,1040.000000
mean,6.979452,3.357115,0.260777,13.842596,7.237500
std,0.403156,3.059524,0.119313,14.994467,6.349186
min,5.610000,0.030000,0.000000,0.300000,0.000000
25%,6.720000,1.350000,0.179000,5.000000,3.000000
50%,6.985000,2.375000,0.264000,8.800000,6.000000
75%,7.250000,4.390000,0.348250,16.200000,10.000000
max,8.220000,24.540000,0.613000,152.800000,43.000000

In [19]:
import os
os.makedirs("data/processed", exist_ok=True)

df.to_csv("data/processed/cleaned_disease_dataset.csv", index=False)
print("Saved. Final shape:", df.shape)

Saved. Final shape: (1040, 18)